/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import Listeners.Navigator;
import Food.Order;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Birdman
 */

public class Card extends javax.swing.JPanel {

    
    private
    Navigator navigator;
    Order order;
    Split split;
    
    /**
     * 
     * Creates new form Card
     */
    public Card(Navigator navigator, Order order) {
        initComponents();
        setSize(1024, 768);
        this.navigator = navigator;
        this.order = order;
        
        JLabel paid = new JLabel("You paid with a card!", JLabel.CENTER);
        paid.setFont(new Font("Serif", Font.PLAIN, 24));
        paid.setForeground(Color.YELLOW);
        
        
        add(paid);
       

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setBackground(new java.awt.Color(153, 0, 0));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
