/*
 * CSCE 4444
 * 
 * 
 */
package Panels;
import Listeners.Navigator;
import javafx.scene.control.MenuButton;
import javax.swing.JLabel;

/*
CREATING A NEW PANEL
1> Navigator.Java class
        + Create new gotTo() method
            - This will create a problem in the App.Java class
2> App.Java class
        + Impliment all abstract methods
        + Add these methods:
            - setContentPane(new PanelObject(this)) 
            - repaint();
            -revalidate();
3> Create new Panel
        + Add Navigator field
        + Add Navigator object to the Panel's constructor argument
        + Set this.navigator = passed constructor argument
4> Add Listener to button in new Panel
        + In ButtonMouseClicked method:
            - Call navigator.goTo method for destination



*/

public class HomeScreen extends javax.swing.JPanel {
    
    private Navigator navigator;

    public HomeScreen(Navigator navigator) {
        initComponents();   
        setSize(1024, 768);
        this.navigator = navigator;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuButton1 = new javax.swing.JLabel();
        gamesButton = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 0));
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));

        menuButton1.setBackground(new java.awt.Color(204, 0, 0));
        menuButton1.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        menuButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuButton1.setText("MENU");
        menuButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        menuButton1.setOpaque(true);
        menuButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuButton1MouseClicked(evt);
            }
        });

        gamesButton.setBackground(new java.awt.Color(204, 0, 0));
        gamesButton.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        gamesButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gamesButton.setText("GAMES");
        gamesButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gamesButton.setOpaque(true);
        gamesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gamesButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gamesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gamesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(424, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menuButton1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_menuButton1MouseClicked
    {//GEN-HEADEREND:event_menuButton1MouseClicked
        // TODO add your handling code here:
        navigator.goToMenu();
    }//GEN-LAST:event_menuButton1MouseClicked

    private void gamesButtonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_gamesButtonMouseClicked
    {//GEN-HEADEREND:event_gamesButtonMouseClicked
        // TODO add your handling code here:
        navigator.goToGames();
    }//GEN-LAST:event_gamesButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gamesButton;
    private javax.swing.JLabel menuButton1;
    // End of variables declaration//GEN-END:variables
}
