/*
 * CSCE 4444
 * 
 * 
 */
package Panels;

import Food.Food;
import Listeners.Navigator;
import Listeners.OrderItemDetailsListener;
import javax.swing.JLabel;
import javax.swing.JPanel;
import Panels.Drinks;
import Panels.Desserts;
import Panels.Entrees;
import Panels.Appetizers;

public class OrderItemDetails extends javax.swing.JPanel
{
    
    OrderItemDetailsListener listener;
    Food item; 
    Navigator navigator;
    JPanel current;
    /**
     * Creates new form OrderItemDetails
     */
    public OrderItemDetails(Food item, OrderItemDetailsListener listener,Navigator navigator)
    {
        initComponents();
        setSize(270, 270);
        this.listener = listener;
        this.item = item;
        this.navigator = navigator;
        itemName.setText(item.GetName());//Display the name
        itemPrice.setText((Double.toString(item.GetPrice())));//Display the price
        
        //Display the ingredients
        for(int i = 0; i < item.getIngrediantArraySize(); i++)
        {
            itemIngredients.add(new JLabel(item.GetIngredients(i)));
        }
    }
    
    
    //UPDATE ORDER ITEM DETAILS PANEL
    public void updateOrderItem(Food item)
    {
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        itemName = new javax.swing.JLabel();
        itemPrice = new javax.swing.JLabel();
        itemIngredients = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0), 2));
        setOpaque(false);
        setSize(new java.awt.Dimension(270, 130));
        addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itemName.setFocusable(false);
        add(itemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 40));
        add(itemPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 50, 40));

        itemIngredients.setOpaque(false);
        itemIngredients.setLayout(new javax.swing.BoxLayout(itemIngredients, javax.swing.BoxLayout.Y_AXIS));
        add(itemIngredients, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 200, 190));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_formMouseClicked
    {//GEN-HEADEREND:event_formMouseClicked
        // TODO add your handling code here:
              
         if(item.getItemCatagory().equals("appetizer"))//goes to the correct panels
         { 
            // if (current != Appetizers)
             navigator.goToAppetizers();
             listener.modifyItem(item);
         }
         if(item.getItemCatagory().equals("entree"))
         {
                navigator.goToEntrees();
                listener.modifyItem(item);
         }
         if(item.getItemCatagory().equals( "dessert"))
         {
                navigator.goToDesserts();
                listener.modifyItem(item);
         }
         if(item.getItemCatagory().equals( "drink"))
         {
               
            navigator.goToDrinks();
            listener.modifyItem(item);
           
         }
        
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel itemIngredients;
    private javax.swing.JLabel itemName;
    private javax.swing.JLabel itemPrice;
    // End of variables declaration//GEN-END:variables
}
